"""add persistent transfer quotes

Revision ID: 258cee37eca3
Revises: 94a964ccfbfd
Create Date: 2026-07-25 02:48:33.533157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '258cee37eca3'
down_revision: Union[str, Sequence[str], None] = '94a964ccfbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('rub_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('egp_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_quotes_id'), 'transfer_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_quotes_quote_id'), 'transfer_quotes', ['quote_id'], unique=True)
    op.add_column('transfers', sa.Column('quote_id', sa.String(length=36), nullable=True))
    op.alter_column('transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_transfers_quote_id'), 'transfers', ['quote_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_quote_id'), table_name='transfers')
    op.alter_column('transfers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('transfers', 'quote_id')
    op.drop_index(op.f('ix_transfer_quotes_quote_id'), table_name='transfer_quotes')
    op.drop_index(op.f('ix_transfer_quotes_id'), table_name='transfer_quotes')
    op.drop_table('transfer_quotes')
    # ### end Alembic commands ###
